In [55]:
class Vertex:
    def __init__(self, name):
        self.parent = self  #parent对应节点指针,默认指向它自己
        self.rank = 0 #rank表示子节点的个数
        self.name = name #节点名字
    def  point_to(self, v):  #将指针指向另一个节点
        if v is not None:
            self.parent = v
    def  get_parent(self):  #获取节点指针指向的节点
        return self.parent
    def find(self): #获取集合中的根节点
        x = self
        while x.get_parent() != x:
            x = x.get_parent()
        return x
    def set_rank(self, r):
        self.rank = r
    def get_rank(self):
        return self.rank
    def get_name(self):
        return self.name

In [56]:
def  union(x, y): #x,y是两个连接点集合中的点，该函数将它们所在的集合合并成一个集合
    root_x = x.find()
    root_y = y.find()
    if root_x == root_y:
        return 
    if root_x.get_rank() > root_y.get_rank(): #把高度低的根节点指向高度高的根节点
        root_y.point_to(root_x)
    else:
        root_x.point_to(root_y)
    if root_x.get_rank() == root_y.get_rank(): 
        rank = root_y.get_rank()
        root_y.set_rank(rank + 1)

In [57]:
class  Edge:
    def __init__(self, v1, v2, val):#v1,v2对应边的连接点,val对应边的数值
        self.v1 = v1
        self.v2 = v2
        self.edge_value = val
    def  get_points(self):
        return self.v1, self.v2
    def  get_edge_value(self):
        return self.edge_value
    def  print_edge(self): #打印边的信息
        print("{0}---{1} with value {2}".format(self.v1.get_name(), self.v2.get_name(), self.edge_value))
        

In [117]:
vertexes = []
for i in range(0, 9):  #依据图4-7构建节点
    name = chr(ord("A") + i)
    vertexes.append(Vertex(name))
def  get_vertex_by_name(name):  #根据给定名字从点集合中返回节点
    for v in vertexes:
        if v.get_name() == name:
            return v
    return None

In [118]:
E = []
E_AB = Edge(get_vertex_by_name("A"), get_vertex_by_name("B"), 4)
E.append(E_AB)
E_AH = Edge(get_vertex_by_name("A"), get_vertex_by_name("H"), 8)
E.append(E_AH)
E_BH = Edge(get_vertex_by_name("B"), get_vertex_by_name("H"), 11)
E.append(E_BH)
E_BC = Edge(get_vertex_by_name("B"), get_vertex_by_name("C"), 8)
E.append(E_BC)
E_BH = Edge(get_vertex_by_name("B"), get_vertex_by_name("H"), 11)
E.append(E_BH)
E_CI = Edge(get_vertex_by_name("C"), get_vertex_by_name("I"), 2)
E.append(E_CI)
E_IH = Edge(get_vertex_by_name("I"), get_vertex_by_name("H"), 7)
E.append(E_IH)
E_IG = Edge(get_vertex_by_name("I"), get_vertex_by_name("G"), 6)
E.append(E_IG)
E_HG = Edge(get_vertex_by_name("H"), get_vertex_by_name("G"), 1)
E.append(E_HG)
E_CD = Edge(get_vertex_by_name("C"), get_vertex_by_name("D"), 7)
E.append(E_CD)
E_CF = Edge(get_vertex_by_name("C"), get_vertex_by_name("F"), 4)
E.append(E_CF)
E_DF = Edge(get_vertex_by_name("D"), get_vertex_by_name("F"), 14)
E.append(E_DF)
E_DE = Edge(get_vertex_by_name("D"), get_vertex_by_name("E"), 9)
E.append(E_DE)
E_FE = Edge(get_vertex_by_name("F"), get_vertex_by_name("E"), 10)
E.append(E_FE)
E_GF = Edge(get_vertex_by_name("G"), get_vertex_by_name("F"), 2)
E.append(E_GF)
E.sort(key = lambda x : x.get_edge_value())  #对边按照数值大小进行排序

In [85]:
for e in E:
    e.print_edge()

H---G with value 1
C---I with value 2
G---F with value 2
A---B with value 4
C---F with value 4
I---G with value 6
I---H with value 7
C---D with value 7
A---H with value 8
B---C with value 8
D---E with value 9
F---E with value 10
B---H with value 11
B---H with value 11
D---F with value 14


In [119]:
X = []
cost = 0
for edge in E: #每次选出一条数值最小又能连接切割的边
    u,v = edge.get_points()
    if u.find() != v.find(): #如果边的两个点不在同一个连接点集合内那么就选择该边
        print("Add new edge: ", end = '')
        edge.print_edge()
        X.append(edge)
        union(u, v) #将该线段的两点对应的点集合合并
        cost += edge.get_edge_value()
print("mini spanning tree cost is {0}".format(cost))

Add new edge: H---G with value 1
Add new edge: C---I with value 2
Add new edge: G---F with value 2
Add new edge: A---B with value 4
Add new edge: C---F with value 4
Add new edge: C---D with value 7
Add new edge: A---H with value 8
Add new edge: D---E with value 9
mini spanning tree cost is 37


In [120]:
import heapq
def  get_edges_by_vertex(v): #获得该节点对应的所有边
    edges = []
    for edge in E:
        v1, v2 = edge.get_points()
        if v1 == v or v2 == v:
            edges.append(edge)
    return edges
vertex_count = len(vertexes)
edge_heap = []
v = vertexes.pop() #随机选择一个节点加入集合S
v.selected = True #给节点对象增加一个标志说明它已经被加入到集合S
S = []
S.append(v)
edge_order = 0
edges = get_edges_by_vertex(v)  #获取该节点对应的所有边
for e in edges:  #将加入集合S的点对应的边插入堆
    heapq.heappush(edge_heap, (e.get_edge_value(), edge_order, e))
    edge_order += 1
cost = 0
while len(S) < vertex_count:
    e = heapq.heappop(edge_heap)[2]  #从堆上取得连接集合S和V-S且数值最小的边
    v1, v2 = e.get_points()
    if hasattr(v1, 'selected') is True and hasattr(v2, 'selected') is True: #该边两个节点都已经属于集合S
        continue
    print("Add new edge: ", end = '')
    e.print_edge()
    cost += e.get_edge_value()
    v = v1
    if hasattr(v1, 'selected') is True:  #选出还没有加入集合S的那个点
        v = v2
    v.selected = True
    S.append(v)
    edges = get_edges_by_vertex(v)
    for e in edges:
        v1, v2 = e.get_points()
        if hasattr(v1, 'selected') is False or hasattr(v2, 'selected') is False: #确保加入堆的边是连接连接两个集合的边而不是连接S内部节点的边
            heapq.heappush(edge_heap, (e.get_edge_value(), edge_order, e))
            edge_order += 1
print('mini spanning tree cost : {0}'.format(cost))

Add new edge: C---I with value 2
Add new edge: C---F with value 4
Add new edge: G---F with value 2
Add new edge: H---G with value 1
Add new edge: C---D with value 7
Add new edge: B---C with value 8
Add new edge: A---B with value 4
Add new edge: D---E with value 9
mini spanning tree cost : 37


In [110]:
T = 30  #时间段
N = 20  #任务总数
Tasks = []
for i in range(N):  #初始化每个任务的起始和结束时间
    a = random.randint(0, 30)
    b = random.randint(0, 30)
    Tasks.append([min(a, b), max(a, b)])
Tasks.sort(key = lambda x:x[0], reverse = True)  #将任务按照起始时间降序排列
print("all tasks time intervel are: {0}".format(Tasks))
S = []
for task in Tasks:
    if task[1] <= T:  #选择能在给定时间段内完成且起始时间最晚的任务
        S.append(task)
        T = task[0]  #选择任务后修改时间段
print("the best tasks combination are : {0}".format(S))

all tasks time intervel are: [[28, 29], [19, 23], [17, 23], [12, 18], [11, 19], [11, 26], [10, 13], [10, 20], [8, 11], [7, 26], [6, 18], [6, 13], [4, 9], [4, 22], [3, 12], [3, 17], [2, 5], [1, 11], [1, 21], [0, 9]]
the best tasks combination are : [[28, 29], [19, 23], [12, 18], [8, 11], [2, 5]]


In [2]:
import random

def  arrange_array_by_pivot(array, pivot):
    '''
    将数组分割成三部分，第一部分元素小于pivot,第二部分等于pivot,第三部分大于pivot
    '''
    i = 0
    j = len(array) - 1
    while i < j:  #将数组分成两部分,小于pivot的元素放前面大于pivot的元素放后面
        if array[i] < pivot:
            i += 1
        elif array[i] >= pivot:  
            temp = array[j]
            array[j] = array[i]
            array[i] = temp
            j -= 1
    if array[i] < pivot:
        i += 1
    S1 = array[0 : i]
    k = i
    j = len(array) - 1
    while i < j:  #将余下数组分成两部分，第一部分元素等于pivot,第二部分大于pivot
        if array[i] == pivot:
            i += 1
        else:
            temp = array[j]
            array[j] = array[i]
            array[i] = temp
            j -= 1
    if array[i] == pivot:
        i += 1
    S2 = array[k : i]
    S3 = array[i:]
    return S1, S2, S3
            

def  selection(array, k):
    '''
    查找数组中第k小元素
    '''
    if len(array) <= 1:
        return array[0]
    if k > len(array):
        raise Exception('out of range')
    
    pivot = array[0]
    is_good_pivot = False
    while is_good_pivot != True:
        pivot = random.choice(array)  #随机从数组中选取一个元素做pivot
        S1, S2, S3 = arrange_array_by_pivot(array, pivot)
        if len(S1) <= int((3/4)*len(array)) and len(S3) <= int((3/4)*len(array)):
            is_good_pivot = True
    if len(S1) > 0 and k <= len(S1): #在第一个集合进行递归
        return selection(S1, k)
    elif len(S2) > 0 and k <= len(S1) + len(S2):
        return pivot
    else:
        return selection(S3, k - len(S1) - len(S2))  #在第3个集合中递归
    raise Exception('error')

In [4]:
import random
packet_volumn = 10  #背包容量
item_count = 30  #不同价格的小块数量
items = []
for i in range(item_count):
    items.append(random.randint(10, 100))  #随机设定每种小块的价值
print("items: {0}".format(items))
def  packet_selection(packet_volumn, items):
    m = selection(items, int(len(items) / 2))  #数组根据中位数分成三份，G包含大于m的元素，E包含等于m的元素，L包含小于m的元素
    G = []
    E = []
    L = []
    for item in items:
        if item > m:
            G.append(item)
        elif item == m:
            E.append(item)
        else:
            L.append(item)
    if len(G) > packet_volumn:
        return packet_selection(packet_volumn, G)  #集合G的数量大于背包容量，在集合G上进行递归
    packet = []
    if len(G) == packet_volumn:
        packet.extend(G)
        return packet
    if len(G) + len(E) == packet_volumn:
        packet.extend(G)
        packet.extend(E)
        return packet
    packet.extend(G)
    packet.extend(E)
    packet_volumn -= len(G) + len(E)
    item_from_L = packet_selection(packet_volumn, L)
    packet.extend(item_from_L)
    return packet
packets = packet_selection(packet_volumn, items)
print(packets)

items: [58, 41, 30, 19, 59, 78, 37, 90, 72, 90, 55, 53, 23, 90, 91, 30, 90, 72, 45, 100, 88, 24, 44, 43, 95, 26, 79, 77, 41, 58]
[90, 90, 90, 100, 90, 95, 91, 88, 78, 79]


In [34]:
import numpy as np
packet_volumn = 30
items_count = 20
items = [(0, 0)]
for i in range(items_count + 1): #随机设定物品的大小和价值
    volumn = random.randint(1, 30)  
    value = random.randint(10, 100)
    items.append((volumn, value))
print("item volumn and value: ", items)
C = np.zeros((items_count+1, packet_volumn+1), dtype = np.int)
for i in range(1, items_count+1):  #计算二维表每个元素值
    for j in range(1, packet_volumn + 1):
        item_volumn = items[i][0]
        item_value = items[i][1]
        if item_volumn > j:  
            C[i][j] = C[i-1][j]
        elif C[i-1][j - item_volumn] + item_value >= C[i-1][j]:
            C[i][j] =  C[i-1][j - item_volumn] + item_value 
        else:
            C[i][j] = C[i-1][j]
print("the max value that can put into packet is ", C[items_count][packet_volumn])

item volumn and value:  [(0, 0), (27, 34), (18, 88), (11, 87), (22, 60), (27, 11), (17, 63), (5, 92), (4, 54), (16, 17), (18, 40), (16, 29), (14, 63), (13, 36), (18, 67), (18, 32), (18, 73), (21, 82), (27, 71), (2, 34), (3, 10), (28, 17)]
the max value that can put into packet is  277


In [35]:
i = items_count
j = packet_volumn
packet = []
while i > 0 and j > 0:
    item_volumn = items[i][0]
    item_value = items[i][1]
    if item_volumn > j:
        i -= 1
    elif C[i - 1][j - item_volumn] + item_value >= C[i-1][j]:
            packet.append(i)
            i -= 1
            j -= item_volumn
    else:
        i -= 1
print("items in packet are:")
for item in packet:
    print(items[item])

items in packet are:
(3, 10)
(2, 34)
(4, 54)
(5, 92)
(11, 87)


In [36]:
import numpy as np
import copy 
def  get_greedy_vector(C, value):#获得数值v的最大表示向量
    n = len(C)
    vector = np.zeros((n))
    i = 0
    while i < n :
        if value >= C[i]:
            vector[i] += 1
            value -= C[i]
        else:
            i += 1
    return vector
def  get_value_by_vector(V, C): #通过表示向量获得对应数值
    return np.dot(V, C)
def  get_vector_mode(V):
    mode = 0
    for v in V:
        mode += v
    return mode
def  is_greedy_apply(C):#判断贪婪算法能否适用于数值C给定的硬币值
    C.sort(reverse = True)  #先将数值降序排列
    n = len(C)
    k = 0
    while k < n:
        greedy_vector = get_greedy_vector(C, C[k] - 1)
        vector_w = np.zeros((n))
        k += 1
        for j in range(1, n):  #将第j个分量加1看看得到的值是否满足不等式M(w) < G(w)
            for i in range(j):  #前j-1个分量值相同
                vector_w[i] = greedy_vector[i]
            vector_w[j] = greedy_vector[j] + 1
            w = get_value_by_vector(vector_w, C)
            greedy_vector_w = get_greedy_vector(C, w)
            if get_vector_mode(vector_w) < get_vector_mode(greedy_vector_w):
                return False, w, vector_w, greedy_vector_w
            vector_w[j] -= 1 
    return True, None, None, None  
N = 5
C = random.sample(range(2,50), N - 1)
C.append(1)
print("C is: ", C)
is_apply, w, best_vector, greedy_vector = is_greedy_apply(C)    
if is_apply is False:
    print("greedy algorithm can not apply to {0} with value {1},\
    it is greedy vector is {2} but best vector is {3}".format(C, w, greedy_vector, best_vector))
else:
    print("greedy algorithm can apply to {0}".format(C))

C is:  [44, 13, 34, 33, 1]
greedy algorithm can not apply to [44, 34, 33, 13, 1] with value 68.0,    it is greedy vector is [ 1.  0.  0.  1. 11.] but best vector is [0. 2. 0. 0. 0.]


In [40]:
N = 5
C = random.sample(range(2,50), N - 1)
C.append(1)
print("C is: ", C)
is_apply, w, best_vector, greedy_vector = is_greedy_apply(C)    
if is_apply is False:
    print("greedy algorithm can not apply to {0} with value {1},\
    it is greedy vector is {2} but best vector is {3}".format(C, w, greedy_vector, best_vector))
else:
    print("greedy algorithm can apply to {0}".format(C))

C is:  [39, 45, 10, 35, 1]
greedy algorithm can not apply to [45, 39, 35, 10, 1] with value 78.0,    it is greedy vector is [1. 0. 0. 3. 3.] but best vector is [0. 2. 0. 0. 0.]


In [54]:
cache_size = 8
C = np.zeros((cache_size))
items = 16  #16种不同的数据
item_count = 100  #需要读取100条数据
R = np.zeros((item_count))
for i in range(item_count):
    R[i] = random.randint(1, 17)
item_map = {}
cache_miss = 0
for i in range(len(R)):
    if R[i] in item_map.keys():  #将数据与它在R中位置对应起来
        l = item_map[R[i]]  
        l.append(i)
    else:
        l = []
        l.append(i)
        item_map[R[i]] = l
for i in range(len(R)): #模拟读取每一条数据
    cache_hit = False
    item_save = False
    for c in C:  #检测缓存是否存在要读取的数据
        if c == R[i]:
            cache_hit = True
            break
    if cache_hit is False:
        cache_miss += 1
        for j in range(len(C)):  #如果缓存还有可用空间，将数据放入缓存
            if C[j] == 0:
                C[j] = R[i]
                item_save = True
                item_map[R[i]].pop(0)
                break
        if item_save is False:  #缓存已满，根据最远优先原则置换
            max_distance = 0
            item_selected = 0
            for j in range(len(C)):
                l = item_map[C[j]]
                if len(l) == 0:  #缓存中的元素不会再从R中被读取,因此将其置换出去
                    item_selected = j
                    break
                distance = item_map[C[j]][0]
                if distance > max_distance:
                    max_distance = distance
                    item_selected = j
            C[j] = R[i]  #将离要读取数据最远的缓存数据进行置换
            item_map[R[i]].pop(0)
print("the count of least cache miss is : ", cache_miss)       

the count of least cache miss is :  49


In [56]:
def  edit_distance(x, y, D):
    for j in range(len(y)):
        D[0][j] = j  #对应edit_distance(0, j) = j
    for i in range(len(x)):
        D[i][0] = i  #对应edit_distance(i, 0) = i
    for i in range(1, len(x)):
        for j in range(1, len(y)):  #根据递归表达式D[i][j]的值由D[i-1][j],D[i][j-1],D[i-1][j-1]决定
            diff_xy = 0
            if x[i] != y[j]:
                diff_xy = 1
            D[i][j] = min(1 + D[i-1][j], 1 + D[i][j-1], diff_xy + D[i-1][j-1])
    return D
x = "POLYNOMIAL"
y = "EXPONENTIAL"
D = np.zeros((len(x), len(y)))
D = edit_distance(x, y, D)
print("edit distance table is:\n", D)
print("the smallest edit distance between {0} and {1} is {2}".format(x, y, D[len(x)-1][len(y) - 1]))

edit distance table is:
 [[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  1.  2.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  2.  2.  3.  3.  4.  5.  6.  7.  8.  8.]
 [ 3.  3.  3.  3.  4.  4.  5.  6.  7.  8.  9.]
 [ 4.  4.  4.  4.  3.  4.  4.  5.  6.  7.  8.]
 [ 5.  5.  5.  4.  4.  4.  5.  5.  6.  7.  8.]
 [ 6.  6.  6.  5.  5.  5.  5.  6.  6.  7.  8.]
 [ 7.  7.  7.  6.  6.  6.  6.  6.  6.  7.  8.]
 [ 8.  8.  8.  7.  7.  7.  7.  7.  7.  6.  7.]
 [ 9.  9.  9.  8.  8.  8.  8.  8.  8.  7.  6.]]
the smallest edit distance between POLYNOMIAL and EXPONENTIAL is 6.0


In [60]:
import sys
N = 4 #相乘的矩阵数
M = []
M.append((50, 20))  #构造5.2.1节对应的4个矩阵维度
M.append((20, 1))
M.append((1, 10))
M.append((10, 100))
arrange_map = {} #记录给定i和j对应的最优分割k
C = np.zeros((N, N)).astype(int)
for i in range(N):
    for j in range(N):
        C[i][j] = -1
def  compute_c_table(C, i, j):
    if i < 0 or i >= N:
        return
    if j < 0 or j >= N:
        return
    if i == j:
        C[i][j] = 0
    if C[i][j] != -1:  #当前元素已经计算过
        return C[i][j]
    cost = sys.maxsize 
    best_k = i
    for k in range(i, j):
        first_part_cost = compute_c_table(C, i, k)
        second_part_cost = compute_c_table(C, k + 1, j)
        if first_part_cost + second_part_cost + M[i][0]*M[k][1]*M[j][1] < cost:
            cost = first_part_cost + second_part_cost + M[i][0]*M[k][1]*M[j][1]
            best_k = k 
    C[i][j] = int(cost) 
    arrange_map[(i, j)] = best_k
    return C[i][j]
compute_c_table(C, 0, N-1)
print(C)
print("the best computation time is: ", C[0][N-1])
def  print_best_matrix_arrange(arrange_map, i, j):
    if i == j:
        return "A{0}".format(i)
    if j == i + 1:
        return "(A{0}*A{1})".format(i, j)
    k = arrange_map[(i, j)]  #得到矩阵Ai到Aj连乘时的最优分割
    left = print_best_matrix_arrange(arrange_map, i, k)
    right = print_best_matrix_arrange(arrange_map, k+1, j)
    return "({0}*{1})".format(left, right)
arrangement = print_best_matrix_arrange(arrange_map, 0, N-1)
print("the best arrangement is :", arrangement)

[[   0 1000 1500 7000]
 [  -1    0  200 3000]
 [  -1   -1    0 1000]
 [  -1   -1   -1    0]]
the best computation time is:  7000
the best arrangement is : ((A0*A1)*(A2*A3))


In [61]:
N = 5  #节点数
D = np.zeros((N, N)).astype(int)
S = set()  #对应点的集合
for i in range(1, N):
    S.add(i)
D[0][0] = 0  #根据图5-5进行初始化
D[0][1] = 2
D[0][2] = 4
D[0][3] = 1
D[0][4] = 2
D[1][0] = 3
D[1][1] = 0
D[1][2] = 3
D[1][3] = 2
D[1][4] = 3
D[2][0] = 4
D[2][1] = 3
D[2][2] = 0
D[2][3] = 4
D[2][4] = 2
D[3][0] = 1
D[3][1] = 2
D[3][2] = 4
D[3][3] = 0
D[3][4] = 2
D[4][0] = 2
D[4][1] = 3
D[4][2] = 2
D[4][3] = 2
D[4][4] = 0
def  get_subset(point_set, n): #根据点数构造子集
    if n == 0:
        return []
    sub_sets = [] 
    for p in point_set:
        s = set()
        s.add(p)
        set_copy = point_set.copy()
        set_copy.discard(p)
        sets = get_subset(set_copy, n - 1)
        if len(sets) == 0:
            sub_sets.append(s)
        else:
            for each_set in sets:
                s_union = s.copy().union(each_set)
                sub_sets.append(s_union)
    return sub_sets
def  find_shortest_path():  #计算最短路径
    C = {}
    for point_count in range(1, N):
        sub_sets = get_subset(S.copy(), point_count)  #获得包含给定点数的子集
        for the_set in sub_sets:
            distances = {}  #记录起始点到集合内每一点的最短距离
            for the_point in the_set: #计算当前集合内的点作为回到起始点前一个点时对应的最短距离
                after_discard = the_set.copy()
                after_discard.discard(the_point)
                if len(after_discard) == 0:
                    distances[the_point] = D[0][the_point]
                else:
                    '''
                    如果集合S包含三个点{1,2,3},从节点0开始遍历集合中所有点的最短路径算法为,先找出从起始点0开始遍历集合{1,2},{1,3},{2,3}的最短路径，
                    然后用这三条路径长度分别加上D[2][3],D[3][2],D[3][1]，三个结果中的最小值就是从起始点0开始，遍历集合{1,2,3}中所有点后的最短路径.
                    因此当集合为{1,2,3}时，C[{1,2,3}]对应key值为1，2，3的一个map对象，map[1]表示集合点为{1,2,3}时，遍历路径最后一个节点时1时的最短距离
                    '''
                    set_copy = the_set.copy()
                    set_copy.discard(the_point)
                    distance_to__points = C[frozenset(set_copy)]
                    d = sys.maxsize 
                    for p in set_copy:
                        if D[p][the_point] + distance_to__points[p] < d:
                            d = D[p][the_point] + distance_to__points[p] 
                    distances[the_point] = d
            C[frozenset(the_set)] = distances.copy() #记录起始点到当前集合内每个点的最短距离,根据python语法,fronzenset才能作为key
            distances.clear()
    distances = C[frozenset(S)]
    d = sys.maxsize
    for point in S: #先找到起始点到集合{1,2...n}中对应点的嘴短距离
        if distances[point] + D[point][0] < d:
            d = distances[point] + D[point][0]
    return d, C
shortest_distance, C = find_shortest_path()
print("the shortest distance for visiting all points is : ", shortest_distance)


the shortest distance for visiting all points is :  10


In [62]:
def  find_visiting_path(point_set, C):
    if len(point_set)== 1:
        return [point_set.pop()]
    distances = C[frozenset(point_set)]
    d = sys.maxsize
    path_point = []
    selected_point = None
    for point in S: #先找到起始点到集合{1,2...n}中对应点的嘴短距离
        if distances[point] + D[point][0] < d:
            d = distances[point] + D[point][0]
            selected_point = point 
    point_set.discard(selected_point)
    points_before = find_visiting_path(point_set, C)
    path_point.extend(points_before)
    path_point.extend([selected_point])
    return path_point
points =    find_visiting_path(S, C)
print("the shortest path for visiting all points is : ", points) 

the shortest path for visiting all points is :  [1, 2, 4, 3]


In [64]:
D = np.zeros((3, 3))
D[0][0] = 0.7 #初始化状态转换表
D[0][1] = 0.2
D[0][2] = 0.1
D[1][0] = 0.4
D[1][1] = 0.4
D[1][2] = 0.2
D[2][0] = 0.2
D[2][1] = 0.5
D[2][2] = 0.3
def  viterbi(n):  #计算第一天个状态开始，经过n天后抵达各状态的最大概率
    C = np.zeros((3, 3, n + 1))
    for i in range(3):
        C[i][i][0] = 1
    for k in range(1, n + 1): #根据公式(3)迭代最大概率路径
        for i in range(3):
            for j in range(3):
                C[i][j][k] = max(C[i][0][k - 1] * D[0][j], C[i][1][k-1] * D[1][j], C[i][2][k - 1] * D[2][j])
    return C
n = 4
C = viterbi(n)       
for i in range(3):
    for j in range(3):
        print("the biggest probability from status {0} to status{1} after {2} days is {3}: ".format(i, j, n, C[i][j][n-1]))
def  find_probability_path(i, j , k):  #获得第一天从状态i开始经过k天后抵达状态j的最大概率路径
    path = []
    while k > 0:
        t = 0
        p = C[i][0][k - 1] * D[0][j]
        if C[i][1][k - 1] * D[1][j] > p:
            p = C[i][1][k - 1] * D[1][j]
            t = 1
        if C[i][2][k - 1] * D[1][j] > p:
            p = C[i][1][k - 1] * D[1][j]
            t = 1
        path.append(t)
        k -= 1
    path.reverse()
    path.append(j)
    path.insert(0, i)
    return path
days = 3
i = 2
j = 2
path = find_probability_path(i, j, days - 1)
print("the biggest probability path from status {0} to status{1} after {2} days is : {3}".format(i, j, days, path))

the biggest probability from status 0 to status0 after 4 days is 0.3429999999999999: 
the biggest probability from status 0 to status1 after 4 days is 0.09799999999999999: 
the biggest probability from status 0 to status2 after 4 days is 0.048999999999999995: 
the biggest probability from status 1 to status0 after 4 days is 0.19599999999999998: 
the biggest probability from status 1 to status1 after 4 days is 0.06400000000000002: 
the biggest probability from status 1 to status2 after 4 days is 0.03200000000000001: 
the biggest probability from status 2 to status0 after 4 days is 0.13999999999999999: 
the biggest probability from status 2 to status1 after 4 days is 0.08000000000000002: 
the biggest probability from status 2 to status2 after 4 days is 0.04000000000000001: 
the biggest probability path from status 2 to status2 after 3 days is : [2, 1, 1, 2]
