In [54]:
vertex_list = ['A', 'B', 'E', 'C', 'F', 'D', 'G'] #记录图中所有节点   
graph = {} #记录点与点的连接关系
graph['A'] = ['B', 'E']
graph['B'] = ['C', 'E']
graph['E'] = ['C']
graph['C'] = ['D', 'F']
graph['F'] = ['G']
graph['G'] = ['D']
graph['D'] = ['D']
edges = {}  #记录边长度
edges[('A', 'B')] = 2
edges[('A', 'E')] = 8
edges[('B', 'E')] = 3
edges[('B', 'C')] = 5
edges[('E', 'C')] = 4
edges[('C', 'F')] = 3
edges[('C', 'D')] = 7
edges[('G', 'D')] = 1
edges[('F', 'G')] = 2
edges[('D', 'D')] = 0

In [55]:
from heapdict import heapdict 
import sys
def Dijkstra(s, vertex_list, graph, edges):
    hd = heapdict()
    distance_map = {} #记录起始点到其他所有点的最短距离
    for v in vertex_list:  #将起始节点与其他节点的距离加入小堆
        if v == s:
            hd[(s, v)] = 0
            distance_map[(s, v)] = 0
        else:
            hd[(s, v)] = sys.maxsize 
            distance_map[(s, v)] = sys.maxsize
    edge = hd.peekitem()
    while edge is not None:
        points_in_edge = edge[0]
        second_point = points_in_edge[1]
        update = False
        for connect_point in graph[second_point]:
            edge_len = edges[(second_point, connect_point)]
            if hd[(s, second_point)] + edge_len < distance_map[(s, connect_point)]:
                print("path from {0} to {1} to {2} is shorter with length {3}".format(s, second_point, connect_point, hd[(s, second_point)] + edge_len))
                hd[(s, connect_point)] = hd[(s, second_point)] + edge_len
                distance_map[(s, connect_point)] = hd[(s, second_point)] + edge_len
                update = True
        if update == False:  #一旦堆元素有更新时不能把顶部元素弹出因为被更新后的元素可能恰好处于堆顶
            hd.popitem()
        if hd.__len__() == 0:
            edge = None
        else:
            edge = hd.peekitem()
    return distance_map 

In [56]:
distances = Dijkstra('A', vertex_list, graph ,edges)
for key in distances.keys():
    print("the shortest distance from {0} to {1} is {2}".format(key[0], key[1], distances[key]))

path from A to A to B is shorter with length 2
path from A to A to E is shorter with length 8
path from A to B to C is shorter with length 7
path from A to B to E is shorter with length 5
path from A to C to D is shorter with length 14
path from A to C to F is shorter with length 10
path from A to F to G is shorter with length 12
path from A to G to D is shorter with length 13
the shortest distance from A to A is 0
the shortest distance from A to B is 2
the shortest distance from A to E is 5
the shortest distance from A to C is 7
the shortest distance from A to F is 10
the shortest distance from A to D is 13
the shortest distance from A to G is 12


In [44]:
vertex_list = ['A', 'B', 'E', 'C', 'F', 'D'] #记录图中所有节点   
edges = {}  #记录边长度
edges[('A', 'B')] = 10
edges[('A', 'E')] = 3
edges[('B', 'C')] = 2
edges[('B', 'F')] = -3
edges[('C', 'B')] = -1
edges[('E', 'F')] = 3
edges[('F', 'C')] = 4
edges[('F', 'D')] = 1
edges[('D', 'C')] = 4

In [40]:
def  bellman_ford(s, vertex_list, edges):
    distance = {}
    for v in vertex_list:  #将起始节点与其他节点的距离设置为无穷大
        if v == s:
            distance[(s, v)] = 0
        else:
            distance[(s, v)] = sys.maxsize
    for i in range(len(vertex_list)):  #外层循环对应图中点的数量
        for edge in edges.keys():  #内层循环对应图中边的数量
            u = edge[0]
            v = edge[1]
            if distance[(s, u)] < sys.maxsize and distance[(s, u)] + edges[edge] < distance[(s, v)]:
                distance[(s, v)] = distance[(s, u)] + edges[edge]
                print("from {0} to {1} then to {2} can be shorter with distance {3}".format(s, u, v, distance[(s, v)]))
    for edge in edges.keys(): #检测是否有负环生成
        u = edge[0]
        v = edge[1]
        if distance[(s, v)] > distance[(s, u)] + edges[edge]:
            return None
    return distance
distances = bellman_ford('A', vertex_list, edges)
for d in distances.keys():
    print("the shortest path from A to {0} is {1}".format(d[1], distances[d])) 

from A to A then to B can be shorter with distance 10
from A to A then to E can be shorter with distance 3
from A to B then to C can be shorter with distance 12
from A to B then to F can be shorter with distance 7
from A to E then to F can be shorter with distance 6
from A to F then to C can be shorter with distance 10
from A to F then to D can be shorter with distance 7
from A to C then to B can be shorter with distance 9
the shortest path from A to A is 0
the shortest path from A to B is 9
the shortest path from A to E is 3
the shortest path from A to C is 10
the shortest path from A to F is 6
the shortest path from A to D is 7


In [20]:
import numpy as np
vertex_list = [0, 1, 2, 3, 4, 5, 6, 7, 8] #记录图中所有节点 
edge_vertex = {} #记录相连节点
edge_vertex[0] = [7]
edge_vertex[1] = [0, 2]
edge_vertex[2] = [3,8]
edge_vertex[3] = [5]
edge_vertex[4] = [3]
edge_vertex[5] = [4, 2]
edge_vertex[6] = [5, 7]
edge_vertex[7] = [1]
edge_vertex[8] = [6, 7]
edges = np.zeros((len(vertex_list), len(vertex_list))).astype(int) #记录边的长度
for i in range(len(vertex_list)):
    for j in range(len(vertex_list)):
        edges[i][j] = sys.maxsize
edges[0][1] = 4  
edges[1][7] = 11
edges[7][0] = 8
edges[2][1] = 8
edges[2][5] = 4
edges[3][2] = 7
edges[3][4] = 9
edges[4][5] = 10
edges[5][3] = 14
edges[5][6] = 2
edges[6][8] = 6
edges[8][2] = 2
edges[7][6] = 1
edges[7][8] = 7
path_table = np.zeros((len(vertex_list) + 1, len(vertex_list))).astype(int) #第i行第j列表示从起始点0经过i条边后到达节点j的最短路径长度
for i in range(len(vertex_list) + 1):
    for j in range(len(vertex_list)):
        path_table[i][j] = sys.maxsize
path_table[0][0] = 0 #起始点通过0条边抵达自己

In [21]:
def  compute_path_table(k, v):
    if k < 0 or k > len(vertex_list):
        return sys.maxsize
    if v < 0 or v >= len(vertex_list):
        return sys.maxsize
    if k == 0:
        return path_table[k][v]
    if path_table[k][v] != sys.maxsize:
        return path_table[k][v]
    for u in edge_vertex[v]:  #根据公式(9)进行计算
        s_to_u = compute_path_table(k - 1, u)
        if s_to_u != sys.maxsize  and s_to_u + edges[u][v] < path_table[k][v]:
            print("u: {0}, k: {1}, s_to_u: {2}, s_to_v: {3}".format(u, k, s_to_u, s_to_u + edges[u][v]))
            path_table[k][v] = s_to_u + edges[u][v]
    return path_table[k][v]
for k in range(len(vertex_list) + 1):
    for v in vertex_list:
        compute_path_table(k, v)

u: 0, k: 1, s_to_u: 0, s_to_v: 4
u: 1, k: 2, s_to_u: 4, s_to_v: 15
u: 7, k: 3, s_to_u: 15, s_to_v: 23
u: 7, k: 3, s_to_u: 15, s_to_v: 16
u: 7, k: 3, s_to_u: 15, s_to_v: 22
u: 0, k: 4, s_to_u: 23, s_to_v: 27
u: 8, k: 4, s_to_u: 22, s_to_v: 24
u: 6, k: 4, s_to_u: 16, s_to_v: 22
u: 2, k: 5, s_to_u: 24, s_to_v: 32
u: 8, k: 5, s_to_u: 22, s_to_v: 24
u: 2, k: 5, s_to_u: 24, s_to_v: 28
u: 1, k: 5, s_to_u: 27, s_to_v: 38
u: 7, k: 6, s_to_u: 38, s_to_v: 46
u: 2, k: 6, s_to_u: 24, s_to_v: 32
u: 5, k: 6, s_to_u: 28, s_to_v: 42
u: 2, k: 6, s_to_u: 24, s_to_v: 28
u: 5, k: 6, s_to_u: 28, s_to_v: 30
u: 1, k: 6, s_to_u: 32, s_to_v: 43
u: 7, k: 6, s_to_u: 38, s_to_v: 45
u: 7, k: 7, s_to_u: 43, s_to_v: 51
u: 0, k: 7, s_to_u: 46, s_to_v: 50
u: 3, k: 7, s_to_u: 42, s_to_v: 49
u: 8, k: 7, s_to_u: 45, s_to_v: 47
u: 5, k: 7, s_to_u: 28, s_to_v: 42
u: 3, k: 7, s_to_u: 42, s_to_v: 51
u: 5, k: 7, s_to_u: 28, s_to_v: 30
u: 1, k: 7, s_to_u: 32, s_to_v: 43
u: 6, k: 7, s_to_u: 30, s_to_v: 36
u: 7, k: 8, s_to_u: 43,

In [24]:
mean_circle = []
for v in vertex_list:
    mean_circle.append(-sys.maxsize -1)
for v in vertex_list:
    for k in range(len(vertex_list)):
        if path_table[k][v] != sys.maxsize and path_table[len(vertex_list)][v] != sys.maxsize and ((path_table[len(vertex_list)][v] - path_table[k][v]) / (len(vertex_list) - k)) > mean_circle[v]:
            mean_circle[v] = (path_table[len(vertex_list)][v] - path_table[k][v]) / (len(vertex_list) - k)
minimun_mean_circle = sys.maxsize
for c in mean_circle:
    if c != -sys.maxsize-1 and c < minimun_mean_circle:
        minimun_mean_circle = c
print("the minimun mean circle length is : ", minimun_mean_circle)

the minimun mean circle length is :  3.5


In [25]:
vertex_list = [0, 1, 2, 3, 4, 5, 6, 7, 8] #记录图中所有节点 
edge_vertex = {} #记录相连节点
edge_vertex[0] = [1]
edge_vertex[1] = [7]
edge_vertex[2] = [1, 5]
edge_vertex[3] = [2, 4]
edge_vertex[4] = [5]
edge_vertex[5] = [3, 6]
edge_vertex[6] = [8]
edge_vertex[7] = [6, 8 ,0]
edge_vertex[8] = [2]
edges = np.zeros((len(vertex_list), len(vertex_list))).astype(int) #记录边的长度
for i in range(len(vertex_list)):
    for j in range(len(vertex_list)):
        edges[i][j] = sys.maxsize
edges[0][1] = 4  
edges[1][7] = 11
edges[7][0] = 8
edges[2][1] = 8
edges[2][5] = 4
edges[3][2] = 7
edges[3][4] = 9
edges[4][5] = 10
edges[5][3] = 14
edges[5][6] = 2
edges[6][8] = 6
edges[8][2] = 2
edges[7][6] = 1
edges[7][8] = 7

In [29]:
def  floyd_warshall(vertext_list ,edge_vertex, edges):
    n = len(vertext_list)
    D_0 = np.zeros((n, n)).astype(int)
    P_0 = np.zeros((n, n)).astype(int)  #记录i到j最短路径上处于j前面的节点编号
    for u in vertext_list:
        for v in edge_vertex[u]:  #当k=0时,i,j之间的最短距离就是两者连线
            D_0[u][v] = edges[u][v]
            P_0[u][v] = u  #(u,v)边中排在节点v前面的节点为u
    for i in range(n):
        for j in range(n):
            if D_0[i][j] == 0 and i != j:  #两点间没有连接那么在K=0时他们之间距离为无穷大
                D_0[i][j] = sys.maxsize
    for k in range(1, n):
        D_1 = np.zeros((n, n)).astype(int)
        P_1 = np.zeros((n, n)).astype(int)
        for i in range(n):
            for j in range(n): #根据公式（10）计算
                D_1[i][j] = D_0[i][j]
                P_1[i][j] = P_0[i][j]
                if D_0[i][k] != sys.maxsize and D_0[k][j] != sys.maxsize:
                    D_1[i][j] = min(D_0[i][j], D_0[i][k] + D_0[k][j])
                    if D_0[i][k] + D_0[k][j] < D_0[i][j]:
                        P_1[i][j] = P_0[k][j]
        D_0 = D_1
        P_0 = P_1
    return D_0, P_0
n = len(vertex_list)
D, P = floyd_warshall(vertex_list, edge_vertex, edges)
print(D)

[[ 0  4 24 42 51 28 16 15 22]
 [19  0 20 38 47 24 12 11 18]
 [27  8  0 18 27  4  6 19 12]
 [34 15  7  0  9 11 13 26 19]
 [47 28 20 24  0 10 12 39 18]
 [37 18 10 14 23  0  2 29  8]
 [35 16  8 26 35 12  0 27  6]
 [ 8 17  9 27 36 13  1  0  7]
 [29 10  2 20 29  6  8 21  0]]


In [30]:
def  get_shortest_path(i, j, P):
    path = []
    if i == j:
        path.append(i)
        return path 
    k = P[i][j]
    path.extend(get_shortest_path(i, k ,P))
    path.append(j)
    return path
i = 8
j = 0
p = get_shortest_path(i, j, P)
print("shortest path from {0} to {1} is {2}".format(i, j, p))

shortest path from 8 to 0 is [8, 2, 1, 7, 0]


In [59]:
vertex_list = [0, 1, 2, 3, 4, 5, 6, 7, 8] #记录图中所有节点 
edge_vertex = {} #记录相连节点
edge_vertex[0] = [1]
edge_vertex[1] = [7]
edge_vertex[2] = [1, 5]
edge_vertex[3] = [2, 4]
edge_vertex[4] = [5]
edge_vertex[5] = [3, 6]
edge_vertex[6] = [8]
edge_vertex[7] = [6, 8 ,0]
edge_vertex[8] = [2]
edges = {}
edges[(0, 1)] = 4
edges[(1, 7)] = 11
edges[(7, 0)] = 8
edges[(2, 1)] = -8
edges[(2, 5)] = 4
edges[(3, 2)] = 7
edges[(3, 4)] = -9
edges[(4, 5)] = 10
edges[(5, 3)] = 14
edges[(5, 6)] = 2
edges[(6, 8)] = 6
edges[(8, 2)] = -2
edges[(7, 6)] = 1
edges[(7, 8)] = 7

In [60]:
def  johnson(vertex_list ,edge_vertex,  edges):
    s = len(vertex_list)
    edge_vertex[s] = vertex_list.copy()
    for v in vertex_list:  #新增节点到其他节点的边长为0
        edges[(s, v)] = 0
    vertex_list.append(s) 
    bellman_ford_distance = bellman_ford(s, vertex_list, edges) #计算新节点到其他所有节点的最短距离
    print("shortest path from new point to other points are: ", bellman_ford_distance)
    if bellman_ford_distance == None: #图中含有负环
        print("graph contains negative circle")
        return
    for edge in edges.keys():  #将每条边的长度按照公式（16）进行修正
        d_u = bellman_ford_distance[(s, edge[0])]
        d_v = bellman_ford_distance[(s, edge[1])]
        edges[edge] = edges[edge] + d_u - d_v
    D = []
    for u in vertex_list:
        distance_map = Dijkstra(u, vertex_list, edge_vertex, edges)
        l = []
        for edge in distance_map.keys(): #根据公式（16）做逆运算
            d = distance_map[edge]
            d = d + bellman_ford_distance[(s, edge[1])] - bellman_ford_distance[(s, edge[0])]
            l.append(d)
            print("shortest path from {0} to {1} is {2}".format(edge[0], edge[1], d))
        D.append(l)
    return D

In [61]:
D = johnson(vertex_list, edge_vertex, edges)    

from 9 to 9 then to 0 can be shorter with distance 0
from 9 to 9 then to 1 can be shorter with distance 0
from 9 to 9 then to 2 can be shorter with distance 0
from 9 to 9 then to 3 can be shorter with distance 0
from 9 to 9 then to 4 can be shorter with distance 0
from 9 to 9 then to 5 can be shorter with distance 0
from 9 to 9 then to 6 can be shorter with distance 0
from 9 to 9 then to 7 can be shorter with distance 0
from 9 to 9 then to 8 can be shorter with distance 0
from 9 to 2 then to 1 can be shorter with distance -8
from 9 to 3 then to 4 can be shorter with distance -9
from 9 to 8 then to 2 can be shorter with distance -2
from 9 to 2 then to 1 can be shorter with distance -10
shortest path from new point to other points are:  {(9, 0): 0, (9, 1): -10, (9, 2): -2, (9, 3): 0, (9, 4): -9, (9, 5): 0, (9, 6): 0, (9, 7): 0, (9, 8): 0, (9, 9): 0}
path from 0 to 0 to 1 is shorter with length 14
path from 0 to 1 to 7 is shorter with length 15
path from 0 to 7 to 6 is shorter with length